### PR TITLE
Stabilize test

### PR DESCRIPTION
**Pull request by n0v1**
After #377 was merged I noticed that tests sometimes still fail with `No address added out of total 1 resolved`. I opted to use [get-port](https://www.npmjs.com/package/get-port) module to get real unused ports instead of using just some random number between 1000 and 65000.

With those changes test runs seem stable.

### CODE REVIEW

**Comment by anonrig** [comment]
Can you also remove coveralls from GitHub actions?

**Comment by n0v1** [comment]
Do you mean removing all stuff related to coveralls from .github/workflows/nodejs.yml? I noticed that sending coverage report failed every now and then with `Can't add a job to a build that is already closed.`. This should be fixed now by properly waiting until all parallel runs finished. Should I still remove coveralls?

**Comment by anonrig** [comment]
let's keep it as it is

**Comment by n0v1** [comment]
Thanks for merging! Now that tests are stable, is there any chance to release a new version soon? In particular to make mali compatible with @grpc/grpc-js v1.10.x (fixed by #375).

**Comment by anonrig** [comment]
Yes I'll release a version today. Although, I'm not sure if I still have the permission. cc @bojand

**Comment by bojand** [comment]
Hello, yes you should still have write access to the NPM package. Please proceed.

**Comment by andres06-hub** [comment]
Hi, I think you have not created the version yet, could you help with this please.

**Comment by ScripterSugar** [comment]
reminder ping @anonrig 🙏

**Comment by n0v1** [comment]
@anonrig, @bojand, is there anything blocking a new release including this fix?

**Pull request merged**
